import type { Metadata } from "next";
import { ReportPermalinkView } from "@/components/ReportPermalinkView";
import { loadReportMeta } from "@/lib/reportSummary";

type PageParams = { params: Promise<{ id: string }> };

export async function generateMetadata({ params }: PageParams): Promise<Metadata> {
  const { id } = await params;
  const meta = await loadReportMeta(id);

  if (!meta) {
    return {
      title: "Research Report · GhostResearcher",
      description: "An autonomous web research report generated by GhostResearcher.",
    };
  }

  const pageTitle = `${meta.title} · GhostResearcher`;
  const permalink = `/reports/${id}`;

  // The dynamic og:image is wired automatically by the colocated
  // opengraph-image.tsx file convention — no need to set images here.
  return {
    title: pageTitle,
    description: meta.description,
    alternates: { canonical: permalink },
    openGraph: {
      type: "article",
      title: meta.title,
      description: meta.description,
      url: permalink,
      siteName: "GhostResearcher",
    },
    twitter: {
      card: "summary_large_image",
      title: meta.title,
      description: meta.description,
    },
  };
}

export default async function ReportPermalinkPage({ params }: PageParams) {
  const { id } = await params;
  return <ReportPermalinkView id={id} />;
}
