import { getResearchJob, type ResearchJob } from "@/lib/api";

/**
 * Server-side view of a report used to build social-preview metadata
 * (Open Graph / Twitter cards) and the dynamic `opengraph-image`.
 *
 * Kept separate from the client ReportViewer so it can run inside
 * `generateMetadata` and the image route without pulling in React/DOM code.
 */
export type ReportMeta = {
  title: string;
  description: string;
  confidencePct: number | null;
  sourceCount: number;
  isLongForm: boolean;
};

const DEFAULT_DESCRIPTION = "An autonomous web research report generated by GhostResearcher.";

export function deriveReportMeta(job: ResearchJob): ReportMeta {
  const report = job.synthesis;
  const goal = job.session?.research_goal?.trim() || null;

  const title = report?.title?.trim() || goal || "Research Report";
  const description =
    report?.abstract?.trim() || report?.summary?.trim() || goal || DEFAULT_DESCRIPTION;

  return {
    title: truncate(title, 140),
    description: truncate(description, 200),
    confidencePct: report ? Math.round(report.confidence * 100) : null,
    sourceCount: job.session?.sources_visited?.length ?? 0,
    isLongForm: Boolean(report?.sections && report.sections.length > 0),
  };
}

/**
 * Fetch a job server-side and derive preview metadata. Resilient by design:
 * a missing report or an unreachable API returns null so callers fall back to
 * generic branded metadata instead of failing the request.
 */
export async function loadReportMeta(id: string): Promise<ReportMeta | null> {
  try {
    const job = await getResearchJob(id);
    return deriveReportMeta(job);
  } catch {
    return null;
  }
}

export function truncate(value: string, max: number): string {
  const collapsed = value.replace(/\s+/g, " ").trim();
  if (collapsed.length <= max) {
    return collapsed;
  }
  return `${collapsed.slice(0, max - 1).trimEnd()}…`;
}
